### ISSUE TITLE
can't use MKDX 1.18

### ISSUE THREAD

**Issue by Nessu4K** [Harmmmm/MKDX-English-Mod#5]
Can you have a version for 1.10? I'm not paying to play 1.18

**Comment by lemmingDev** [comment]
https://github.com/Harmmmm/MKDX-English-Mod/releases/tag/v0.6

**Comment by Nessu4K** [comment]
This just proves I don't know how to navigate this site yet XDDD

Thank you so much lemmingDev, I appreciate you o7

**Comment by lemmingDev** [comment]
1.18 can be played without TP at all.
You need a mario kart specific version of jconfig available on emuline
I got it working yesterday, and it works fine with the current Eng mod

I think TP patreon allows more functionality in 1.18 including cloud saving to online profile and perhaps even network play
